version: "3"

services:
  deco:
    build: .
    links:
    - mongo
    ports:
    - "3000:3000"
    environment:
    - DB=mongodb://mongo:27017/deco-db

  mongo:
    image: mongo
    ports:
    - "27017:27017"